name: Release

on:
    schedule:
        - cron: 0 0 * * *

    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            matrix:
                release: [stable, insiders]
        env:
            X_APP_VERSION: ""
            X_TAG_NAME: ""
            X_APP_RELEASE: ${{ matrix.release }}
            X_NEEDS_RELEASE: ""
        steps:
            - uses: actions/checkout@v4

            - name: 🚧 Prerequistes
              run: |
                  sudo apt-get update
                  sudo apt-get install -y podman

            - name: 🔨 Build executables
              run: |
                  find ./scripts -type f -name "*.sh" -exec chmod +x {} \;
                  ./scripts/build-podman.sh $X_APP_RELEASE

            - name: 🔢 Get version
              run: |
                  version=$(cat ./dist/build-version.txt)
                  needs_release=$(./scripts/needs-release.sh | xargs)
                  echo "X_APP_VERSION=${version}" >> $GITHUB_ENV
                  echo "X_TAG_NAME=v${version}" >> $GITHUB_ENV
                  echo "X_NEEDS_RELEASE=${needs_release}" >> $GITHUB_ENV

            - name: 🚀 Upload executables
              uses: ncipollo/release-action@v1
              if: ${{ env.X_NEEDS_RELEASE == 'yes' }}
              with:
                  body: "Visual Studio Code Version: `${{ env.X_APP_VERSION }}`"
                  tag: ${{ env.X_TAG_NAME }}
                  artifacts: "dist/*.AppImage"
                  generateReleaseNotes: false
                  draft: false
                  artifactErrorsFailBuild: true
                  allowUpdates: true
                  replacesArtifacts: true
                  makeLatest: true
                  prerelease: ${{ env.X_APP_RELEASE == 'insiders' }}

    generate-badge:
        needs: [release]
        uses: ./.github/workflows/badges.yml
